=== Marioitic17/practica6/prac.dtd
<!ELEMENT wholeSaleElectronics (stock, wholeSaleClients)>       
<!ELEMENT stock (product)>
<!ELEMENT product (brand, model, price, quantityInStock)>
<!ATTLIST product id ID #REQUIRED category CDATA #REQUIRED quantity CDATA #REQUIRED orderDate CDATA #REQUIRED>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT price EMPTY>
<!ATTLIST price currency CDATA #REQUIRED>
<!ELEMENT quantityInStock (#PCDATA)>
<!ELEMENT wholeSaleClients (client)>
<!ELEMENT client (name, contactPerson, email, phoneNumber, address, orders?)>
<!ATTLIST client id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT contactPerson (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT address (city, country, street, postalCode)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>
<!ELEMENT orders (product)>
<!ELEMENT product EMPTY>
<!ATTLIST product id IDREF #REQUIRED quantity CDATA #REQUIRED orderDate CDATA #REQUIRED category CDATA #REQUIRED>

=== Marioitic17/practica6/prac.xml
<?xml version="1.0"?>
<!DOCTYPE wholeSaleElectronics SYSTEM "prac.dtd">
<wholeSaleElectronics>
    <stock>
        <product id="A050" category="SmartPhoneS">
            <brand>iphone</brand>
            <model>15</model>
            <price currency="euros 1000.00"/>
            <quantityInStock>1300</quantityInStock>
        </product>
    </stock>
    <wholeSaleClients>
        <!-- contains customer details -->
        <client id="B12"/>
        <name>Zepp Electronic</name>
        <!-- name of company -->
        <contactPerson>Carlos Garcia</contactPerson>
        <email>carlosgarcia@zeppelectronics.com</email>
        <!-- email of the contact person -->
        <phoneNumber>682749374</phoneNumber>
        <address>
            <!-- adress of the client -->
            <city>Barcelona</city>
            <country>Spain</country>
            <street>Passeig de Gracia 2</street>
            <postalCode>08029</postalCode>
        </address>
        <orders>
            <!-- contains details of purchased products -->
            <product id="B003" quantity="200" orderDate="4/11/2023"/>
        </orders>
    </wholeSaleClients>
</wholeSaleElectronics>
